server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users_db
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
